apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: skeji-services-personal
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
  - matrix:
      generators:
      - repoURL: https://github.com/nthome0191-debug/Skeji.git
        revision: HEAD
        files:
          - path: "local-personal/*/config.yaml"

  template:
    metadata:
      name: '{{.service}}-{{.developer}}'
      labels:
        app: '{{.service}}-{{.developer}}'
        environment: 'local'
    spec:
      project: skeji-personal

      source:
        repoURL: https://github.com/nthome0191-debug/Skeji.git
        targetRevision: '{{.branch}}'
        path: deployment/charts/{{.service}}
        helm:
          valueFiles:
          - ../../values/local/{{.service}}.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: apps-{{.developer}}

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas
